name: cred
description: Credit Loan App
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  expandable: ^5.0.1
  sleek_circular_slider: ^2.0.1
  intl: ^0.18.0
  neopop: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
     - assets/images/

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy/Gilroy-Bold.ttf
        - asset: assets/fonts/Gilroy/Gilroy-Medium.ttf
        - asset: assets/fonts/Gilroy/Gilroy-Regular.ttf
        - asset: assets/fonts/Gilroy/Gilroy-SemiBold.ttf
        - asset: assets/fonts/Gilroy/Gilroy-Thin.ttf
    - family: OverpassMono
      fonts:
        - asset: assets/fonts/OverpassMono/OverpassMono-Bold.ttf
        - asset: assets/fonts/OverpassMono/OverpassMono-Light.ttf
        - asset: assets/fonts/OverpassMono/OverpassMono-Medium.ttf
        - asset: assets/fonts/OverpassMono/OverpassMono-Regular.ttf
        - asset: assets/fonts/OverpassMono/OverpassMono-SemiBold.ttf
    - family: Cirka
      fonts:
        - asset: assets/fonts/Cirka/Cirka-Bold.otf
        - asset: assets/fonts/Cirka/Cirka-Light.otf
        - asset: assets/fonts/Cirka/Cirka-Variable.ttf